version: '3.8'

services:
  king-17:
    image: david-17
    build: .
    ports:
      - '7001:7000'
    environment:
      - MONGODB_URI:'mongodb://localhost:27017/ticket'
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
